# -*- coding: utf-8 -*-
"""Bayesian_Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ln7JXEkigZ8qGjK_tF2L8OcvGQMIwOhl

# Learning the topology of a Bayesian Network from a database of cases using the K2 algorithm

Structure: (any remarks/ suggestions?)
- introducing algorithm & functions
- introducing node ordering
- test data sets (Ruiz, Asia, Child)
  - compare ground truth to k2 network
  - compare our k2 vs bnstruct
- heart disease data set
  - compare k2 to bnstruct
"""

# should we remove this cell for the hand-in later?
install.packages(c("bnlearn", "bnstruct", "latex2exp","ggplot2","gtools","arules","dplyr","purrr","r.blip"))
install.packages("BiocManager")
BiocManager::install("Rgraphviz")

# Load necessary libraries
library("ggplot2")
library("latex2exp")
library("bnlearn")
library("bnstruct")
library("Rgraphviz")
library("dplyr")
library("arules")
library("gtools")
library("r.blip")
library("digest")
library("purrr")

"""Importing the necessary libraries:"""

# Load necessary libraries
library("ggplot2") %>% suppressPackageStartupMessages()
library("latex2exp") %>% suppressPackageStartupMessages()
library("bnlearn") %>% suppressPackageStartupMessages()
library("bnstruct") %>% suppressPackageStartupMessages()
library("Rgraphviz") %>% suppressPackageStartupMessages()
library("dplyr") %>% suppressPackageStartupMessages()
library("arules") %>% suppressPackageStartupMessages()
library("gtools") %>% suppressPackageStartupMessages()
library("r.blip") %>% suppressPackageStartupMessages()

"""## The K2 algorithm
*TODO: How are we going to handle sources/bibliography? How do we create a bibliography in a .ipynb notebook? Also, someone please check this*

The K2 algorithm [[Cooper/Herskovits](https://doi.org/10.1007/BF00994110)] is a heuristic search-method to find  the most probable Bayesian belief-network structure, given a database of records. It assumes an ordering of the attributes, where, if attribute $x_i$ precedes $x_j$ in the order, structures with an arc from $x_j$ to $x_i$ (so $x_i$ being a parent of $x_j$) are not allowed. Additionally, equal priors are assumed for all the allowed belief network structures that are possible.

The algorithm can be described as follows:

**Input:**  A set of nodes $n$, an ordering of the nodes,  an upper bound $u$ on the number of parents a node may have, and a database $D$ containing $m$ cases.

**Output:** For each node, a printout of the parents of the node.

$$
\begin{array}{rl}
1. & \textbf{procedure} \ \text{K2}\\
2. & \textbf{for} \; i \gets 1 \; \textbf{to} \; n \; \textbf{do} \\
3. & \quad \pi_i \gets \emptyset \\
4. & \quad P_{\text{old}} \gets g(i, \pi_i) \; \{ \text{scoring function} \} \\
5. & \quad \text{OKToProceed} \gets \textbf{true} \\
6. & \quad \textbf{while} \; \text{OKToProceed} \; \textbf{and} \; |\pi_i| < u \; \textbf{do} \\
7. & \quad \quad \text{Let} \; z \; \text{be the node in Pred}(x_i) - \pi_i \; \text{that maximizes} \; g(i, \pi_i \cup \{z\}) \\
8. & \quad \quad P_{\text{new}} \gets g(i, \pi_i \cup \{z\}) \\
9. & \quad \quad \textbf{if} \; P_{\text{new}} > P_{\text{old}} \; \textbf{then} \\
10. & \quad \quad \quad P_{\text{old}} \gets P_{\text{new}} \\
11. & \quad \quad \quad \pi_i \gets \pi_i \cup \{z\} \\
12. & \quad \quad \textbf{else} \\
13. & \quad \quad \quad \text{OKToProceed} \gets \textbf{false} \\
14. & \quad \textbf{end while}\\
15. & \quad \textbf{write}(\text{'Node:'},\, x_i,\, \text{'Parents of this node:'}, \, \pi_i) \\
16. & \textbf{end for}\\
17. & \textbf{end} \; \text{K2}\\
\end{array}
$$

### The scoring function $g(i, \pi_i)$
The scoring function $g(i, \pi_i)$ for the K2 algorithm as described in [[Ruiz](http://web.cs.wpi.edu/~cs539/s11/Projects/k2_algorithm.pdf)] is defined as
$$
g(i, \pi_i) = \prod^{q_i}_{j=1}\frac{\left(r_i-1\right)!}{\left(N_{ij} + r_i -1\right)!} \prod^{r_i}_{k=1}\alpha_{ijk}! \ ,
$$
where
- $\pi_i$: set of parents of $i$-th node, here called $x_i$
- $q_i = |\phi_i|$
- $\phi_i$: list of all possible instantiations of the parents of $x_i$ in database $D$. That is, if $p_1, \dots , p_s$ are the parents of $x_i$ then $\phi_i$ is the Cartesian product $\{v_1^{p_1}, \dots, v_{r_{p_1}}^{p_1}\}\times \dots \times\{v_1^{p_s}, \dots, v_{r_{p_s}}^{p_s}\}$ of all the possible values of attributes $p_1$ through $p_s$.
- $r_i = |V_i|$
- $V_i$: list of all possible values of the attribute $x_i$
- $\alpha_{ijk}$: number of cases (i.e. instances) in $D$ in which the attribute $x_i$ is instantiated with its $k$th value, and the parents of $x_i$ in $\pi_i$ are instantiated with the $j$th instantiation in $\phi_i$.
- $N_{ij} = \sum^{r_i}_{k=1}\alpha_{ijk}$. That is, the number of instances in the database in which the parents of $x_i$ in $\pi_i$ are instantiated with the $j$th instantiation in $\phi_i$.

The scoring function was implemented as follows:
"""

# k2 scoring function
k2_score <- function(node, parents, df) {

    # r: number of possible values for node
    r <- nlevels(df[[node]])

    # handle case of no parents:
    # (which we assume if parents has length 0)
    # ignore the 'j'
    if (length(parents) == 0) {
        # get all possible instantiations
        instantiations <- df %>%
            group_by(across(all_of(node))) %>%
            summarize(counts=n(), .groups='drop') %>%
            mutate(factorials=factorial(counts)) # to calculate alpha_i_k

        N <- sum(instantiations$counts)
        alpha <- prod(instantiations$factorials)
        numerator <- alpha*(factorial(r-1))
        denominator <- factorial(N+r-1)

    }
    else {

        # q:  total number of possible combinations for parent nodes
        q <- prod(sapply(df[parents], nlevels))

        # get all possible instantiations
        instantiations <- df %>%
            group_by(across(all_of(c(node, parents)))) %>%
            summarize(counts=n(), .groups='drop') %>%
            mutate(factorials=factorial(counts)) # to calculate alpha_ijk

        # get all possible instantiations of parents
        instantiations.parents <- instantiations %>%
            group_by(across(all_of(parents))) %>%
            summarize(N=sum(counts), .groups='drop') %>% # to calculate N_ij
            mutate(d = factorial(N+r-1))

        alpha <- prod(instantiations$factorials)
        numerator <- alpha*(factorial(r-1))^q
        denominator <- prod(instantiations.parents$d)
    }
    score <- numerator/denominator
    return(score)

}

"""To improve the run-time speed of K2 and avoid the computation of large factorials, the logarithm of the scoring function  $\log{\left(g(i,\pi_i)\right)}$ can be used instead. Computing the logarithmic version relies on addition and subtraction instead:
$$
\begin{align}
\log{\left(g(i,\pi_i)\right)} &= \log{\left(\prod^{q_i}_{j=1}\frac{\left(r_i-1\right)!}{\left(N_{ij} + r_i -1\right)!} \prod^{r_i}_{k=1}\alpha_{ijk}! \right)} \\
&= \sum^{q_i}_{j=1} \log{ \left( \frac{\left(r_i-1\right)!}{\left(N_{ij} + r_i -1\right)!} \prod^{r_i}_{k=1}\alpha_{ijk}!  \right) } \\
&= \sum^{q_i}_{j=1} \left[ \log{\left(\left(r_i-1\right)!\right)} - \log{\left(\left(N_{ij} + r_i -1\right)! \right)} + \log{\left( \prod^{r_i}_{k=1}\alpha_{ijk}! \right)} \right] \\
&= \sum^{q_i}_{j=1} \left[ \sum^{r_i-1}_{l=1} \log{l} - \sum^{N_{ij} + r_i -1}_{m=1} \log{m} + \sum^{r_i}_{k=1} \sum^{\alpha_{ijk}}_{n=1}\log{n} \right]
\end{align}
$$
"""

# logarithmic version of the scoring function
k2_score.log <- function(node, parents, df) {

    # r: number of possible values for node
    r <- nlevels(df[[node]])

    # handle case of no parents:
    # (which we assume if parents has length 0)
    # ignore the 'j'
    if (length(parents) == 0) {
        # get all possible instantiations
        instantiations <- df %>%
            group_by(across(all_of(node))) %>%
            summarize(counts=n(), .groups='drop') %>%
            mutate(c=map_dbl(counts, ~ sum(log(1:.x))))

        N <- sum(instantiations$counts)

        # calculate the summands
        A <- sum(log(1:(r-1)))
        B <- sum(log(1:(N+r-1)))
        C <- sum(instantiations$c)
    }
    else {
        # q:  total number of possible combinations for parent nodes
        q <- prod(sapply(df[parents], nlevels))

        # get all possible instantiations
        instantiations <- df %>%
            group_by(across(all_of(c(node, parents)))) %>%
            summarize(counts=n(), .groups='drop') %>%
            mutate(c=map_dbl(counts, ~ sum(log(1:.x)))) #

        # get all possible instantiations of parents
        instantiations.parents <- instantiations %>%
            group_by(across(all_of(parents))) %>%
            summarize(N=sum(counts), .groups='drop') %>%
            mutate(b = map_dbl(N, ~ sum(log(1:(.x+r-1)))))

        # calculate the summands
        A <- q*sum(log(1:(r-1)))
        B <- sum(instantiations.parents$b)
        C <- sum(instantiations$c)
    }
    score <- A - B + C
    return(score)
}

"""The implementation of the K2 algorithm, using the custom score function (either normal or logarithmic version):"""

K2Result <- function(best_score, bn) {
  structure(list(score = best_score, bn = bn), class = "K2Result")
}

k2_algorithm.custom_score <- function(data, node_order, max_parents = 3, useLogScore=TRUE) {

    # select either regular or logarithmic scoring function
    if (useLogScore){
        score <- k2_score.log
    }
    else {
        score <- k2_score
    }

    # Initialize an empty Bayesian network with nodes in the given order
    bn <- empty.graph(node_order)

    # Iterate over each node in the given order
    for (node in node_order) {
        # Initialize an empty set of parents for the current node
        parents <- character(0)
        # Compute the initial score of the current network
        # note: this uses the logarithm of the K2 score (k2),
        # a Dirichlet posterior density (not score equivalent).
        best_score <- score(node, parents, data)

        # Try adding parents while the number of parents is less than max_parents
        while (length(parents) < max_parents) {
            best_candidate <- NULL
            best_candidate_score <- best_score

            # Evaluate each potential new parent
            for (candidate_parent in node_order[1:which(node_order==node)]) {
                if (!candidate_parent %in% parents && candidate_parent != node) {
                    # Temporarily add the candidate parent and compute the new score
                    test_bn <- set.arc(bn, from = candidate_parent, to = node)
                    candidate_score <- score(node, c(parents, candidate_parent), data)

                    # Check if the new score is better than the best score found so far
                    if (candidate_score > best_candidate_score) {
                        best_candidate <- candidate_parent
                        best_candidate_score <- candidate_score
                    }
                }
            }

            # If a best candidate parent is found, add it to the network
            if (!is.null(best_candidate)) {
                bn <- set.arc(bn, from = best_candidate, to = node)
                parents <- c(parents, best_candidate)
                parents(bn, node) <- parents
                best_score <- best_candidate_score
            } else {
                break  # No better parent found, stop adding parents
            }
        }
    }

    # Return the learned Bayesian network and the its score
    return(K2Result(best_score,bn))
}

"""Note: should we keep the version below? YES that's the corrected version It's the same as above but with the bnlearn scoring"""

# K2 algorithm using the logarithmic k2 score as implemented in the bnlearn library
# note that the score for the entire network is computed at each iteration
k2_algorithm <- function(data, node_order, max_parents = 3) {
  bn <- empty.graph(node_order)

  for (node in node_order) {
    parents <- character(0)
    best_score <- score(bn, data, type = "k2")

    while (length(parents) < max_parents) {
      best_candidate <- NULL
      best_candidate_score <- best_score

      candidate_parents <- node_order[1:(which(node_order == node) - 1)]
      print(candidate_parents)
      print(node)
      for (candidate_parent in candidate_parents) {
        if (!candidate_parent %in% parents && candidate_parent != node) {
        #if (!candidate_parent %in% parents) {
          test_bn <- set.arc(bn, from = candidate_parent, to = node)
          candidate_score <- score(test_bn, data, type = "k2")

          if (candidate_score > best_candidate_score) {
            best_candidate <- candidate_parent
            best_candidate_score <- candidate_score
          }
        }
      }

      if (!is.null(best_candidate)) {
        bn <- set.arc(bn, from = best_candidate, to = node)
        parents <- c(parents, best_candidate)
        best_score <- best_candidate_score
      } else {
        break
      }
    }
  }

  return(bn)
}

"""### Node ordering
(add description of problem & strategy here)
(Insert relevant function definitions in cell below)

## Test Data Sets
To test the implementation of the K2 algorithm and evaluate its performance, it is used on three test data sets of varying sizes, each generated from a known Bayesian Network structure:
- RUIZ Dataset: 3 nodes, 2 arcs, 10 records
- ASIA Dataset: 8 nodes, 8 arcs, using 5000 records
- CHILD Dataset: 20 nodes, 25 arcs, using 5000 records

The network structures found through the implemented K2 algorithm are evaluated in comparison with the respective ground truth.
Furthermore, the results of the K2 implementation are compared to those of (TODO: Look up what exactly the bnstruct function/algorithm is we're comparing it to).

### RUIZ dataset
(Node: start by showing the ground truth?)
The RUIZ dataset consists of 10 records of 3 attributes $x_1$, $x_2$, $x_3$. It was generated by [[Cooper/Herskovits 1992]](https://doi.org/10.1007/BF00994110) and further used in [[Ruiz]](http://web.cs.wpi.edu/~cs539/s11/Projects/k2_algorithm.pdf) to illustrate the K2 algorithm. The data are generated from a Bayesian network with the structure shown below:
"""

# Create the dataset
data_ruiz <- data.frame(
  x1 = as.factor(c(1, 1, 0, 1, 0, 0, 1, 0, 1, 0)),
  x2 = as.factor(c(0, 1, 0, 1, 0, 1, 1, 0, 1, 0)),
  x3 = as.factor(c(0, 1, 1, 1, 0, 1, 1, 0, 1, 0))
)

# Define node order
node_order_ruiz <- c("x1", "x2", "x3")
#ground truth
dag_ruiz = model2network("[x1][x2|x1][x3|x2]")

graphviz.plot(dag_ruiz,main="ruiz network")

"""### ASIA dataset

The ASIA dataset is a synthetic dataset about lung diseases from [[Lauritzen/Spiegelhalter 1988]](https://doi.org/10.1111/j.2517-6161.1988.tb01721.x). It is included in the `bnlearn` library and contains the following (2-level factor) attributes:
- `D` (dyspnoea)
- `T` (tuberculosis)
- `L` (lung cancer)
- `B` (bronchitis)
- `A` (visit to Asia)
- `S` (smoking)
- `X` (chest X-ray)
- `E` (tuberculosis versus lung cancer/bronchitis)

"""

data(asia)
# ground truth network structure.
dag_asia = model2network("[A][S][T|A][L|S][B|S][D|B:E][E|T:L][X|E]")

# Define the node order for the Asia dataset
node_order_asia <- colnames(asia)

#plot
graphviz.plot(dag_asia,main="asia network")

"""### CHILD dataset
The CHILD Dataset [[Spiegelhalter/Cowell 1992]](https://doi.org/10.1093/oso/9780198522669.003.0025) is a medical dataset about congenital conditions potentially leading to a "blue" baby. It consists of 20 attributes:
- `V1` BirthAsphyxia, Levels: 0 1 2 3
- `V2` HypDistrib, Levels: 0 1 2
- `V3` HypoxiaInO2, Levels: 0 1 2 3
- `V4` CO2 Levels: 0 1 2
- `V5` ChestXray, Levels: 0 1 2 3 4
- `V6` Grunting, Levels: 0 1 2 3 4 5
- `V7` LVHreport, Levels: 0 1 2 3 4 5 6
- `V8` LowerBodyO2, Levels: 0 1 2 3
- `V9` RUQO2, Levels: 0 1 2
- `V10` CO2Report, Levels: 0 1 2
- `V11` XrayReport, Levels: 0 1 2
- `V12` Disease, Levels: 0 1 2 3
-  `V13` GruntingReport, Levels: 0 1 2
- `V14` Age, Levels: 0 1 2
- `V15` LVH, Levels: 0 1 2 3
- `V16` DuctFlow, Levels: 0 1 2 3
- `V17` CardiacMixing, Levels: 0 1 2 3
- `V18` LungParench, Levels: 0 1 2 3
- `V19` LungFlow, Levels: 0 1 2
- `V20` Sick, Levels: 0 1 2 3 4 5

(Note: ...Do I have to look up what all of these mean or can we pretend this is fine? )

I think we can check this article: https://cse.sc.edu/~mgv/csce582sp23/links/SDLC_CHILD_1993.pdf (also to better understand why the predicted label is first)
but only at the end if we have time.
Right now I think its good :)
"""

head(child)

data(child)
# ground truth network structure.
dag_names = model2network("[BirthAsphyxia][Disease|BirthAsphyxia][Sick|Disease][DuctFlow|Disease][CardiacMixing|Disease][LungParench|Disease][LungFlow|Disease][LVH|Disease][Age|Disease:Sick][Grunting|Sick:LungParench][HypDistrib|CardiacMixing:DuctFlow][HypoxiaInO2|CardiacMixing:LungParench][CO2|LungParench][ChestXray|LungParench:LungFlow][LVHreport|LVH][GruntingReport|Grunting][LowerBodyO2|HypDistrib:HypoxiaInO2][RUQO2|HypoxiaInO2][CO2Report|CO2][XrayReport|ChestXray]")

dag_child = model2network("[V1][V12|V1][V20|V12][V16|V12][V17|V12][V18|V12][V19|V12][V15|V12][V14|V12:V20][V6|V20:V18][V2|V17:V16][V3|V17:V18][V4|V18][V5|V18:V19][V7|V15][V13|V6][V8|V2:V3][V9|V3][V10|V4][V11|V5]")

data("child")
# Define the node order for the Child dataset
node_order_child <- colnames(child)

#plot
graphviz.plot(dag_names)
graphviz.plot(dag_child)

"""## Dependence on Node Ordering
#### example

The K2 Algorithm is extremely dependent on the input ordering of data.

Here is provided a simple illustration with the asia dataset.


(I'll leave these here until we decide how to handle bibliography)

<a name="article 1"></a>1. [A Bayesian Method for the Induction of Probabilistic Networks from Data](https://link.springer.com/article/10.1007/bf00994110)

<a name="article 2"></a>2. [Illustration of the K2 Algorithm for Learning Bayes Net Structures](https://web.cs.wpi.edu/~cs539/s05/Projects/k2_algorithm.pdf)

<a name="node ordering - article 3"></a>3. [Improved K2 algorithm for Bayesian network structure learning](https://www.sciencedirect.com/science/article/pii/S095219762030083X)

Firstly the ground truth topology is compared with the topology generated from optimal ordering
"""

bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.compare(dag_asia,bn_asia,main=c("ground truth","comparison"))

"""Then with one generated from a random ordering"""

node_order_asia <- c("A",sample(colnames(asia)[-1]))
#results with a random order
bn_asia <- empty.graph(node_order_asia)

# Run the K2 algorithm on the Asia dataset
bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.compare(dag_asia,bn_asia,main=c("ground truth","comparaison"))

"""To overcome this problem a randomized algorithm has been implemented.
For t iterations a random order of the variablesis generated (the only constraint is that the classification target should be placed first, as suggested in <a name="article 2"></a><sup>[[1]</sup>](https://web.cs.wpi.edu/~cs539/s05/Projects/k2_algorithm.pdf)). Then an associate netowrk is created using the k2 algorithm.
The best network is the one with higher k2 score.

## Begin Ignore

##### 1) Brute force with a toy dataset (<a name="RUIZ article"></a>[RUIZ](http://web.cs.wpi.edu/~cs539/s11/Projects/k2_algorithm.pdf))
In first place the Ruiz dataset is built and the topology is learned with k2 algorithm.
"""

# Create the dataset
data_ruiz <- data.frame(
  x1 = as.factor(c(1, 1, 0, 1, 0, 0, 1, 0, 1, 0)),
  x2 = as.factor(c(0, 1, 0, 1, 0, 1, 1, 0, 1, 0)),
  x3 = as.factor(c(0, 1, 1, 1, 0, 1, 1, 0, 1, 0))
)

# Define node order
node_order <- c("x1", "x2", "x3")
#ground truth
dag = model2network("[x1][x2|x1][x3|x2]")

bn <- k2_algorithm(data_ruiz, node_order)
# Print the resulting Bayesian network
print(bn)
graphviz.compare(dag,bn,main=c("Network generated with k2 algorithm","ground truth Network"))

"""The result is then compared with the one obtained by the best ordering:"""

BNSearchResult <- function(scores, bn_list) {
  structure(list(scores = scores, bn_v = bn_list), class = "BNSearchResult")
}

bf_search <- function(data, node_order, target_node, ref = NULL, t = 100, custom=FALSE,plot = FALSE) {
  target_idx <- which(node_order == target_node)
  target_node <- node_order[target_idx]

  n <- length(node_order)
  node_order_r <- node_order[-target_idx]  # Reduced node order (we know that the target node must be the first)
  t <- min(t, factorial(n - 1))

  scores <- list()
  bn_list <- list()

  if (!is.null(ref)) {
    scores$tp <- rep(0, t)  # True positives
    scores$fp <- rep(0, t)  # False positives
    scores$fn <- rep(0, t)  # False negatives
    scores$h <- rep(0, t)  # Hamming distance between the true network and the one we generate
    scores$shd <- rep(0, t)  # Structural Hamming distance (SHD)
  } else {
    scores <- rep(0, t)  # Initialize scores as a numeric vector if ref is NULL
  }

  used_permutations <- new.env(hash = TRUE, parent = emptyenv())  # Use an environment to store unique permutations

  for (k in 1:t) {
    repeat {
      node_order_r_sample <- sample(node_order_r)  # Sample a permutation
      perm_hash <- digest(node_order_r_sample)  # Generate a hash of the permutation

      if (!exists(perm_hash, envir = used_permutations)) {
        assign(perm_hash, TRUE, envir = used_permutations)  # Mark the permutation as used
        break
      }
    }

    node_order <- c(target_node, node_order_r_sample)
    ifelse(custom==TRUE,bn_list[[k]] <- k2_algorithm.custom_score(data, node_order)$bn,bn_list[[k]] <- k2_algorithm(data, node_order))

    if (plot) {
      graphviz.plot(bn_list[[k]], main = sprintf("node order: %s", paste(node_order, collapse = ', ')))
    }

    # Evaluate the result
    if (!is.null(ref)) {
      comp <- compare(ref, bn_list[[k]])
      scores$tp[k] <- comp$tp
      scores$fp[k] <- comp$fp
      scores$fn[k] <- comp$fn
      scores$h[k] <- hamming(ref, bn_list[[k]])
      scores$shd[k] <- shd(ref, bn_list[[k]])
    } else {
      if(custom==TRUE) {
        sum(sapply(nodes(bn_list[[k]]),function(N) {k2_score.log(N,parents(bn_list[[k]],N),data)}))
        } else {
          scores[k] <-score(bn_list[[k]], data, type = "k2")
        }
    }
  }
  return(BNSearchResult(scores, bn_list))
}

results <- bf_search(data=data_ruiz,node_order=node_order,target_node="x1",ref=dag,plot=TRUE)
scores <- results$scores
bn_v <- results$bn_v

"""We choose the best network:"""

min <- which(scores$h==min(scores$h))[1]

# ground truth network structure.
dag = model2network("[A][S][T|A][L|S][B|S][D|B:E][E|T:L][X|E]")

# Define the node order for the Asia dataset
colnames(asia)

node_order_asia <- colnames(asia)
bn_asia <- empty.graph(node_order_asia)

# Run the K2 algorithm on the Asia dataset
bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.plot(bn_asia,main="learned network")
#fitted_asia_bn <- bn.fit(bn_asia, asia) #fit with an already implemented method
#graphviz.plot(fitted_asia_bn)
graphviz.compare(dag,bn_asia,main=c("ground truth network","comparaison"))

"""#### 1) Improvement of BF with small datasets (<a name="ASIA article"></a>[ASIA](https://www.eecis.udel.edu/~shatkay/Course/papers/Lauritzen1988.pdf))"""

#asia dataset
a_d <- read.csv('https://www.ccd.pitt.edu/wiki/images/ASIA10k.csv') #ASIA dataset
head(a_d)

"""The procedure is repeated with the ASIA dataset

The procedure of learning the topology with the K2 algorithm obtains satisfying results
for more complicated (even if still small) datasets:
"""

# ground truth network structure.
dag = model2network("[A][S][T|A][L|S][B|S][D|B:E][E|T:L][X|E]")

# Define the node order for the Asia dataset
node_order_asia <- colnames(asia)
#results with a random order
bn_asia <- empty.graph(node_order_asia)

# Run the K2 algorithm on the Asia dataset
bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.plot(bn_asia,main="learned topology")
#fitted_asia_bn <- bn.fit(bn_asia, asia) #fit with an already implemented method
#graphviz.plot(fitted_asia_bn)
graphviz.compare(dag,bn_asia,main=c("ground truth","comparaison"))

"""The results are less satisfactory when we change the order of the variables:"""

node_order_asia <- c("A",sample(colnames(asia)[-1]))
#results with a random order
bn_asia <- empty.graph(node_order_asia)

# Run the K2 algorithm on the Asia dataset
bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.plot(bn_asia,main="learned topology")
#fitted_asia_bn <- bn.fit(bn_asia, asia) #fit with an already implemented method
#graphviz.plot(fitted_asia_bn)
graphviz.compare(dag,bn_asia,main=c("ground truth","comparaison"))

"""The results are quite satisfacotry with a simple randomized search for the best order:"""

results <- bf_search(asia,node_order_asia,"A",dag,300)
scores <- results$scores
bn_v <- results$bn_v
cat("True positives: \n")
cat(scores$tp)
cat("\n")
cat("False negatives: \n")
cat(scores$fn)
cat("\n")
cat("False positives: \n")
cat(scores$fp)
cat("\n")
cat("Hamming distances: \n")
cat(scores$h)
cat("\n")
cat("Structural hamming distances: \n")
cat(scores$shd)
cat("\n")

id <- which(scores$h==min(scores$h))[1]
graphviz.compare(dag,bn_v[[id]],main=c("ground truth topology","comparaison"))

"""## end ignore

### Heart Disease Dataset
(Note: still don't know how we're best handling citations here, for now I'll just add this link to at least keep an overview. Also, is this the correct subset of attributes used?)

The [UCI Heart Disease Dataset](https://doi.org/10.24432/C52P4X) contains attributes that are considered relevant for predicting heart disease in patients. The attributes are listed  below:

1. `id` (Unique id for each patient)
2. `age` (Age of the patient in years)
3. `origin` (place of study)
4. `sex` (Male/Female)
5. `cp` chest pain type ([typical angina, atypical angina, non-anginal, asymptomatic])
6. `trestbps` resting blood pressure (resting blood pressure (in mm Hg on admission to the hospital))
7. `chol` (serum cholesterol in mg/dl)
8. `fbs` (if fasting blood sugar > 120 mg/dl)
9. `restecg` (resting electrocardiographic results) --  Values: [normal, stt abnormality, lv hypertrophy]
10. `thalach`: maximum heart rate achieved
11. `exang` exercise-induced angina (True/ False)
12. `oldpeak` ST depression induced by exercise relative to rest
13. `slope` the slope of the peak exercise ST segment
14. `ca`: number of major vessels (0-3) colored by fluoroscopy
15. `thal`: [normal; fixed defect; reversible defect]
16. `num`: the predicted attribute

Note that `id` and `origin` were excluded from the analysis, as they are assumed to be irrelevant for the presence of heart disease.
"""

# Load the dataset
#data <- read.csv("heart_disease_uci.csv")
data <- read.csv("heart_disease_uci.csv")

# Remove the id and dataset columns
data <- data %>% select(-id, -dataset)

# Inspect the column names
colnames(data)

# Identify numeric columns based on actual column names
numeric_columns <- c("age", "trestbps", "chol", "thalch", "oldpeak")

# Verify numeric columns exist in the data
missing_columns <- setdiff(numeric_columns, colnames(data))
if (length(missing_columns) > 0) {
  stop(paste("The following columns are missing from the dataset:", paste(missing_columns, collapse = ", ")))
}

# Convert relevant columns to numeric
data[numeric_columns] <- lapply(data[numeric_columns], as.numeric)

# Check for missing values
sapply(data, function(x) sum(is.na(x)))

# Handle missing values, e.g., by removing rows with missing data or imputing
data <- na.omit(data)

# Preprocess the data: Discretize continuous variables
data$age <- discretize(data$age, method = "interval", breaks = 3)
data$trestbps <- discretize(data$trestbps, method = "interval", breaks = 3)
data$chol <- discretize(data$chol, method = "interval", breaks = 3)
data$thalch <- discretize(data$thalch, method = "interval", breaks = 3)
data$oldpeak <- discretize(data$oldpeak, method = "interval", breaks = 3)

# Convert categorical variables to factors
data$sex <- as.factor(data$sex)
data$cp <- as.factor(data$cp)
data$fbs <- as.factor(data$fbs)
data$restecg <- as.factor(data$restecg)
data$exang <- as.factor(data$exang)
data$slope <- as.factor(data$slope)
data$ca <- as.factor(data$ca)
data$thal <- as.factor(data$thal)
data$num <- as.factor(data$num)  # Assuming 'num' is the target variable

# Verify the preprocessing results
summary(data)

# Define node order
node_order <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalch", "exang", "oldpeak", "slope", "ca", "thal", "num")

# Run the K2 algorithm
bn <- k2_algorithm(data, node_order)

node_order_h <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalch", "exang", "oldpeak", "slope", "ca", "thal","num")
results <- bf_search(data,node_order_h,"num",t=100,custom=TRUE)
scores <- results$scores
bn_v <- results$bn_v

id <- which(scores==max(scores))[1]
graphviz.plot(bn_v[[id]],main="learned topology")

install.packages("bnlearn")
install.packages("dplyr")
install.packages("arules")
library(bnlearn)
library(dplyr)
library(arules)

plot(bn)

graphviz.plot(bn)

# Create the dataset
data_ruiz <- data.frame(
  x1 = as.factor(c(1, 1, 0, 1, 0, 0, 1, 0, 1, 0)),
  x2 = as.factor(c(0, 1, 0, 1, 0, 1, 1, 0, 1, 0)),
  x3 = as.factor(c(0, 1, 1, 1, 0, 1, 1, 0, 1, 0))
)

# Define node order
node_order <- c("x1", "x2", "x3")
bn <- k2_algorithm(data_ruiz, node_order)
# Print the resulting Bayesian network
print(bn)
graphviz.plot(bn)

# Ensure data is a data frame
data <- as.data.frame(data)

# Example: Predict the probability of heart disease (num) given some evidence
evidence <- list(age = "[45,61)", sex = "Male", cp = "typical angina", trestbps = "[129,165)", chol = "[188,376)", thalch = "[115,158)", oldpeak = "[2.07,4.13)")

# Convert the evidence to a logical expression
evidence_expr <- paste(names(evidence), "==", sapply(evidence, function(x) paste0('"', x, '"')), collapse = " & ")

# Query the network
prediction <- cpquery(fitted = fitted_bn, event = (num == "1"), evidence = (eval(parse(text = evidence_expr))))
print(prediction)

# Example: Predict the probability of heart disease (num) given some evidence
evidence <- list(age = "[45,61)", sex = "Female", cp = "typical angina", trestbps = "[129,165)", chol = "[188,376)", thalch = "[115,158)", oldpeak = "[2.07,4.13)")

# Convert the evidence to a logical expression
evidence_expr <- paste(names(evidence), "==", sapply(evidence, function(x) paste0('"', x, '"')), collapse = " & ")

# Query the network
prediction <- cpquery(fitted = fitted_bn, event = (num == "1"), evidence = (eval(parse(text = evidence_expr))))
print(prediction)

# Cross-validation
cv.bnlearn <- bn.cv(bn, data, k = 10, runs = 10)

data("asia")
# Define the node order for the Asia dataset
colnames(asia)

node_order_asia <- colnames(asia)

# Run the K2 algorithm on the Asia dataset
bn_asia <- k2_algorithm(asia, node_order_asia)
graphviz.plot(bn_asia)
fitted_asia_bn <- bn.fit(bn_asia, asia)

install.packages("bnstruct")
library("bnstruct")
data("child")
# Define the node order for the Asia dataset
colnames(child)

node_order_child <- colnames(child)

# Run the K2 algorithm on the Asia dataset
bn_child<- k2_algorithm(child, node_order_child)
graphviz.plot(bn_child)
fitted_child_bn <- bn.fit(bn_child, child)

install.packages("r.blip")
library(r.blip)

data("child")
# Define the node order for the Child dataset
node_order_child <- colnames(child)

# Run the K2 algorithm on the Child dataset
bn_child <- k2_algorithm(child, node_order_child)
graphviz.plot(bn_child)
fitted_child_bn <- bn.fit(bn_child, child)

install.packages("bnstruct")
library(bnstruct)
# Impute missing values if necessary
imputed_data <- impute_knn(data)

# Learn the structure using bnstruct
bn_bnstruct <- learn.network(imputed_data, algo = "mmhc")

# Compare the structures
compare(bn, bn_bnstruct)

# Example: Predict the probability of heart disease (num) given some evidence
evidence <- list(age = "[45,61)", sex = "Male", cp = "typical angina", trestbps = "[129,165)", chol = "[188,376)", thalch = "[115,158)", oldpeak = "[2.07,4.13)")

# Query the network
prediction <- cpquery(fitted = fitted_bn, event = (num == "1"), evidence = evidence)
print(prediction)

"""### Functions to be deleted?"""

#############DO NOT RUN##############################
k2_algorithmy <- function(data, node_order, max_parents = 3) {
  bn <- empty.graph(node_order)
  for (node in node_order) {
    parents <- character(0)
    best_score <- score(bn, data, type = "k2")
    while (length(parents) < max_parents) {
      best_candidate <- NULL
      best_candidate_score <- best_score
      for (candidate_parent in node_order[node_order < node]) {
        if (!candidate_parent %in% parents) {
          test_bn <- set.arc(bn, from = candidate_parent, to = node)
          candidate_score <- score(test_bn, data, type = "k2")
          if (candidate_score > best_candidate_score) {
            best_candidate <- candidate_parent
            best_candidate_score <- candidate_score
          }
        }
      }
      if (!is.null(best_candidate)) {
        bn <- set.arc(bn, from = best_candidate, to = node)
        parents <- c(parents, best_candidate)
        best_score <- best_candidate_score
      } else {
        break
      }
    }
  }
  return(bn)
}


# Define node order
node_order <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalch", "exang", "oldpeak", "slope", "ca", "thal", "num")

# Run the K2 algorithm
bn <- k2_algorithm(data, node_order)

#############DO NOT RUN##############################
k2_algorithmx <- function(data, node_order, max_parents = 3) {
  bn <- empty.graph(node_order)
  for (node in node_order) {
    parents <- character(0)
    best_score <- score(bn, data, type = "k2")
    while (length(parents) < max_parents) {
      best_candidate <- NULL
      best_candidate_score <- best_score
      for (candidate_parent in node_order[which(node_order == node) - 1:1]) {
        if (!candidate_parent %in% parents) {
          test_bn <- set.arc(bn, from = candidate_parent, to = node)
          candidate_score <- score(test_bn, data, type = "k2")
          if (candidate_score > best_candidate_score) {
            best_candidate <- candidate_parent
            best_candidate_score <- candidate_score
          }
        }
      }
      if (!is.null(best_candidate)) {
        bn <- set.arc(bn, from = best_candidate, to = node)
        parents <- c(parents, best_candidate)
        best_score <- best_candidate_score
      } else {
        break
      }
    }
  }
  return(bn)
}

# Define node order
node_order <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalch", "exang", "oldpeak", "slope", "ca", "thal", "num")

# Run the K2 algorithm
bn <- k2_algorithm(data, node_order)

####################NOT TO RUN#########################
k2_algorithm.custom_score <- function(data, node_order, max_parents = 3, useLogScore=TRUE) {

    # select either regular or logarithmic scoring function
    if (useLogScore){
        score <- k2_score.log
    }
    else {
        score <- k2_score
    }

    # Initialize an empty Bayesian network with nodes in the given order
    bn <- empty.graph(node_order)

    # Iterate over each node in the given order
    for (node in node_order) {
        # Initialize an empty set of parents for the current node
        parents <- character(0)
        # Compute the initial score of the current network
        # note: this uses the logarithm of the K2 score (k2),
        # a Dirichlet posterior density (not score equivalent).
        best_score <- score(node, parents, data)

        # Try adding parents while the number of parents is less than max_parents
        while (length(parents) < max_parents) {
            best_candidate <- NULL
            best_candidate_score <- best_score

            # Evaluate each potential new parent
            for (candidate_parent in node_order[1:which(node_order==node)]) {
                if (!candidate_parent %in% parents && candidate_parent != node) {
                    # Temporarily add the candidate parent and compute the new score
                    test_bn <- set.arc(bn, from = candidate_parent, to = node)
                    candidate_score <- score(node, c(parents, candidate_parent), data)

                    # Check if the new score is better than the best score found so far
                    if (candidate_score > best_candidate_score) {
                        best_candidate <- candidate_parent
                        best_candidate_score <- candidate_score
                    }
                }
            }

            # If a best candidate parent is found, add it to the network
            if (!is.null(best_candidate)) {
                bn <- set.arc(bn, from = best_candidate, to = node)
                parents <- c(parents, best_candidate)
                best_score <- best_candidate_score
            } else {
                break  # No better parent found, stop adding parents
            }
        }
    }

    # Return the learned Bayesian network
    print(best_score)
    return(bn)
}

# Create the dataset
ruiz <- data.frame(
  x1 = as.factor(c(1, 1, 0, 1, 0, 0, 1, 0, 1, 0)),
  x2 = as.factor(c(0, 1, 0, 1, 0, 1, 1, 0, 1, 0)),
  x3 = as.factor(c(0, 1, 1, 1, 0, 1, 1, 0, 1, 0))
)


# Set the maximum number of parents
max_parents <- 1

# Learn the structure using the K2 algorithm
#k2_model_ruiz <- hc(ruiz, score = "k2", maxp = max_parents)
k2_model_ruiz <- tabu(ruiz, score = "k2")
# Print the learned structure
print(k2_model_ruiz)

# Plot the Bayesian Network
plot(k2_model_ruiz)

graphviz.plot(k2_model_ruiz)
graphviz.compare(dag_ruiz,k2_model_ruiz,main=c("ground truth","comparison"))

data("asia")

# Set the maximum number of parents
max_parents <- 3

# Learn the structure using the K2 algorithm
#k2_model_asia <- hc(asia, score = "k2", maxp = max_parents)
k2_model_asia <- tabu(asia, score = "k2")
# Print the learned structure
print(k2_model_asia)

# Plot the Bayesian Network
plot(k2_model_asia)

graphviz.plot(k2_model_asia)
graphviz.compare(dag_asia, k2_model_asia,main=c("ground truth","comparison"))

install.packages("r.blip")
library(r.blip)
data("child")

# Set the maximum number of parents
max_parents <- 3

# Learn the structure using the K2 algorithm
k2_model_child <- hc(child, score = "k2", maxp = max_parents)

# Print the learned structure
print(k2_model_child)

# Plot the Bayesian Network
plot(k2_model_child)

graphviz.plot(k2_model_child)
graphviz.compare(dag_child,k2_model_child,main=c("ground truth","comparison"))

heart <- read.csv("heart_disease_uci.csv")
# Remove the id and dataset columns
heart <- heart %>% select(-id, -dataset)

# Inspect the column names
colnames(heart)

# Identify numeric columns based on actual column names
numeric_columns <- c("age", "trestbps", "chol", "thalch", "oldpeak")

# Verify numeric columns exist in the data
missing_columns <- setdiff(numeric_columns, colnames(heart))
if (length(missing_columns) > 0) {
  stop(paste("The following columns are missing from the dataset:", paste(missing_columns, collapse = ", ")))
}

# Convert relevant columns to numeric
heart[numeric_columns] <- lapply(heart[numeric_columns], as.numeric)

# Check for missing values
sapply(heart, function(x) sum(is.na(x)))

# Handle missing values, e.g., by removing rows with missing data or imputing
heart <- na.omit(heart)

# Preprocess the data: Discretize continuous variables
heart$age <- discretize(heart$age, method = "interval", breaks = 3)
heart$trestbps <- discretize(heart$trestbps, method = "interval", breaks = 3)
heart$chol <- discretize(heart$chol, method = "interval", breaks = 3)
heart$thalch <- discretize(heart$thalch, method = "interval", breaks = 3)
heart$oldpeak <- discretize(heart$oldpeak, method = "interval", breaks = 3)

# Convert categorical variables to factors
heart$sex <- as.factor(heart$sex)
heart$cp <- as.factor(heart$cp)
heart$fbs <- as.factor(heart$fbs)
heart$restecg <- as.factor(heart$restecg)
heart$exang <- as.factor(heart$exang)
heart$slope <- as.factor(heart$slope)
heart$ca <- as.factor(heart$ca)
heart$thal <- as.factor(heart$thal)
heart$num <- as.factor(heart$num)  # Assuming 'num' is the target variable

# Set the maximum number of parents
max_parents <- 3
node_order <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalch", "exang", "oldpeak", "slope", "ca", "thal", "num")
# Create a whitelist based on node order

whitelist <- NULL
for (i in 1:(length(node_order) - 1)) {
  for (j in (i + 1):min(i + 3, length(node_order))) {  # Allow up to 3 parents
    whitelist <- rbind(whitelist, c(node_order[i], node_order[j]))
  }
}
# Convert to matrix with appropriate column names
colnames(whitelist) <- c("from", "to")
# Define blacklist to prevent age and sex from being parents of each other
blacklist <- matrix(c("age", "sex",
                      "sex", "age",
                      "chol", "sex",
                      "thal", "sex",
                      "thalch", "age",
                      "ca", "age",
                      "fbs", "age",
                      "trestbps", "age",
                      "chol", "age"),
                    byrow = TRUE, ncol = 2)

#colnames(blacklist) <- c("from", "to")
# Learn the structure using the K2 algorithm
#k2_model_heart <- hc(heart, score = "k2", maxp = max_parents)
#k2_model_heart <- hc(heart, score = "k2", maxp = max_parents, whitelist = whitelist, blacklist = blacklist)
k2_model_heart <- tabu(heart, score = "k2", blacklist = blacklist)
# Print the learned structure
print(k2_model_heart)

# Plot the Bayesian Network
plot(k2_model_heart)

graphviz.plot(k2_model_heart)

# Define the structure manually
dag_string <- paste0("[age][sex][cp|age:sex][trestbps|age:sex:cp][chol|age:sex:cp:trestbps]",
                     "[fbs|age:sex:cp:trestbps:chol][restecg|age:sex:cp:trestbps:chol:fbs]",
                     "[thalch|age:sex:cp:trestbps:chol:fbs:restecg]",
                     "[exang|age:sex:cp:trestbps:chol:fbs:restecg:thalch]",
                     "[oldpeak|age:sex:cp:trestbps:chol:fbs:restecg:thalch:exang]",
                     "[slope|age:sex:cp:trestbps:chol:fbs:restecg:thalch:exang:oldpeak]",
                     "[ca|age:sex:cp:trestbps:chol:fbs:restecg:thalch:exang:oldpeak:slope]",
                     "[thal|age:sex:cp:trestbps:chol:fbs:restecg:thalch:exang:oldpeak:slope:ca]",
                     "[num|age:sex:cp:trestbps:chol:fbs:restecg:thalch:exang:oldpeak:slope:ca:thal]")

# Create the network from the string
custom_dag <- model2network(dag_string)

# Fit the custom network to the data
fitted_dag <- bn.fit(custom_dag, heart)

# Print the fitted network
print(fitted_dag)

# Plot the Bayesian Network
plot(custom_dag)

# Plot using graphviz
graphviz.plot(custom_dag)